[tools]
python = "3.12"
uv = "latest"

[env]
_.python.venv = { path = ".venv", create = true }

[tasks.setup]
description = "Setup"
run = "uv pip install bleak crcmod cryptography"

[tasks.main]
depends = ["setup"]
run = "python loop.py"

[tasks.clean]
description = "TODO"
run = []
